export const CODE_THEMES = [
  { name: "Andromeeda", id: "andromeeda" },
  { name: "Aurora X", id: "aurora-x" },
  { name: "Ayu Dark", id: "ayu-dark" },
  { name: "Ayu Light", id: "ayu-light" },
  { name: "Ayu Mirage", id: "ayu-mirage" },
  { name: "Catppuccin Frappé", id: "catppuccin-frappe" },
  { name: "Catppuccin Latte", id: "catppuccin-latte" },
  { name: "Catppuccin Macchiato", id: "catppuccin-macchiato" },
  { name: "Catppuccin Mocha", id: "catppuccin-mocha" },
  { name: "Dark Plus", id: "dark-plus" },
  { name: "Dracula Theme", id: "dracula" },
  { name: "Dracula Theme Soft", id: "dracula-soft" },
  { name: "Everforest Dark", id: "everforest-dark" },
  { name: "Everforest Light", id: "everforest-light" },
  { name: "GitHub Dark", id: "github-dark" },
  { name: "GitHub Dark Default", id: "github-dark-default" },
  { name: "GitHub Dark Dimmed", id: "github-dark-dimmed" },
  { name: "GitHub Dark High Contrast", id: "github-dark-high-contrast" },
  { name: "GitHub Light", id: "github-light" },
  { name: "GitHub Light Default", id: "github-light-default" },
  { name: "GitHub Light High Contrast", id: "github-light-high-contrast" },
  { name: "Gruvbox Dark Hard", id: "gruvbox-dark-hard" },
  { name: "Gruvbox Dark Medium", id: "gruvbox-dark-medium" },
  { name: "Gruvbox Dark Soft", id: "gruvbox-dark-soft" },
  { name: "Gruvbox Light Hard", id: "gruvbox-light-hard" },
  { name: "Gruvbox Light Medium", id: "gruvbox-light-medium" },
  { name: "Gruvbox Light Soft", id: "gruvbox-light-soft" },
  { name: "Horizon", id: "horizon" },
  { name: "Horizon Bright", id: "horizon-bright" },
  { name: "Houston", id: "houston" },
  { name: "Kanagawa Dragon", id: "kanagawa-dragon" },
  { name: "Kanagawa Lotus", id: "kanagawa-lotus" },
  { name: "Kanagawa Wave", id: "kanagawa-wave" },
  { name: "LaserWave", id: "laserwave" },
  { name: "Light Plus", id: "light-plus" },
  { name: "Material Theme", id: "material-theme" },
  { name: "Material Theme Darker", id: "material-theme-darker" },
  { name: "Material Theme Lighter", id: "material-theme-lighter" },
  { name: "Material Theme Ocean", id: "material-theme-ocean" },
  { name: "Material Theme Palenight", id: "material-theme-palenight" },
  { name: "Min Dark", id: "min-dark" },
  { name: "Min Light", id: "min-light" },
  { name: "Monokai", id: "monokai" },
  { name: "Night Owl", id: "night-owl" },
  { name: "Night Owl Light", id: "night-owl-light" },
  { name: "Nord", id: "nord" },
  { name: "One Dark Pro", id: "one-dark-pro" },
  { name: "One Light", id: "one-light" },
  { name: "Plastic", id: "plastic" },
  { name: "Poimandres", id: "poimandres" },
  { name: "Red", id: "red" },
  { name: "Rosé Pine", id: "rose-pine" },
  { name: "Rosé Pine Dawn", id: "rose-pine-dawn" },
  { name: "Rosé Pine Moon", id: "rose-pine-moon" },
  { name: "Slack Dark", id: "slack-dark" },
  { name: "Slack Ochin", id: "slack-ochin" },
  { name: "Snazzy Light", id: "snazzy-light" },
  { name: "Solarized Dark", id: "solarized-dark" },
  { name: "Solarized Light", id: "solarized-light" },
  { name: "Synthwave '84", id: "synthwave-84" },
  { name: "Tokyo Night", id: "tokyo-night" },
  { name: "Vesper", id: "vesper" },
  { name: "Vitesse Black", id: "vitesse-black" },
  { name: "Vitesse Dark", id: "vitesse-dark" },
  { name: "Vitesse Light", id: "vitesse-light" },
] as const;

export type CodeTheme = (typeof CODE_THEMES)[number]["id"];

export const DEFAULT_CODE_THEME: CodeTheme = "github-dark-default";
